# Generated by Django 4.2.5 on 2024-06-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrip',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
