# Generated by Django 4.2.5 on 2024-06-10 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_usertrip_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='trip_photos/')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='base.trip')),
            ],
        ),
    ]
