# Generated by Django 4.2.5 on 2024-06-10 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_tripphoto_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripPhoto',
        ),
    ]
